### ISSUE TITLE
How to properly include this package in a Flutter project?

### ISSUE THREAD

**Issue by tomekit** [hugo-pcl/native-crypto-flutter#4]
I am wondering how to include this in a Flutter project.

pubspec.yaml
```
native_crypto:
    git:
      url: https://github.com/hugo-pcl/native-crypto-flutter.git
      ref: master
      path: packages/native_crypto
```

main.dart
```
import 'package:native_crypto/native_crypto.dart';
```

I get plenty errors similar to these:
```
../../../snap/flutter/common/flutter/.pub-cache/git/native-crypto-flutter-8f4041d7bfc67b1426c6d2901816066e34acd49d/packages/native_crypto/lib/src/utils/hash_algorithm.dart:30:15: Error: The getter 'NativeCryptoExceptionCode' isn't defined for the class 'HashAlgorithm'.
 - 'HashAlgorithm' is from 'package:native_crypto/src/utils/hash_algorithm.dart' ('../../../snap/flutter/common/flutter/.pub-cache/git/native-crypto-flutter-8f4041d7bfc67b1426c6d2901816066e34acd49d/packages/native_crypto/lib/src/utils/hash_algorithm.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'NativeCryptoExceptionCode'.
        code: NativeCryptoExceptionCode.platform_throws.code,
              ^^^^^^^^^^^^^^^^^^^^^^^^^
```

What am I doing wrong? 
Thanks

**Comment by dv30fps** [comment]
The following works for me:

pubspec.yaml

```
native_crypto:
    git:
      url: https://github.com/hugo-pcl/native-crypto-flutter.git
      ref: native_crypto-v0.1.1
      path: packages/native_crypto
```

Dart code:
```
import 'package:native_crypto/native_crypto.dart';
```

@hugo-pcl : Thanks for adding GCM support!
